name: Deploy to InfinityFree via FTP

on:
  push:
    branches:
      - master

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 🎉 Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftpupload.net
          username: if0_41082809
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          server-dir: /htdocs/
          exclude: |
            **/.git*
            **/.git*/**
            .github/**
            README.md
            *.sql
            img/uploads/**
            admin/videos/uploads/**
            admin/audios/uploads/**
